import type { Metadata } from "next";
import "@/styles/css/style.css";
import Image from "next/image";
import Inner from "@/components/Inner";
import VoteTimer from '@/components/VoteTimer';

export const metadata: Metadata = {
    title: "최애의 전당",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="ko">
            <body>
                <Header />
                {children}
            </body>
        </html>
    );
}

function Header() {


    return (
        <header>
            <Inner x="between">
                <h1>최애의 전당</h1>
                <div>
                    <VoteTimer/>
                    <div className="menu-btn">
                        <Image
                            src="/icons/hamburger.png"
                            width="32"
                            height="32"
                            alt="메뉴버튼"
                        />
                    </div>
                </div>
            </Inner>
        </header>
    );
}
